### ISSUE TITLE
Termo de Abertura de Projeto

### ISSUE THREAD

**Issue by eng-Bruno** [fga-eps-mds/Tema-02#10]
# Descrição
Elaborar termo de abertura de projeto.

# Tarefas
- [x] Definir modelo a ser seguido
- [x] Iniciar termo de abertura do projeto
- [x] Implementar quadro com as funções dos integrantes das equipes
- [x] Implemtar tabela com histórico de versões

# Critérios de aceitação
- [x] Revisão do documento
- [x] Subir documento no git

**Comment by laisramos123** [comment]
#### Alguns links de bibliografias sobre o conceito e a elaboração do Termo de Abertura do Projeto:

- [O que é TAP e como montar o seu](https://artia.com/blog/termo-de-abertura-do-projeto)
- [Modelo de TAP](https://asana.com/pt/resources/project-charter)
- [Modelos de TAP PMKB](https://pmkb.com.br/artigos/modelos-de-termo-de-abertura-de-projeto/)

**Comment by eng-Bruno** [comment]
Documento feito, revisado e disponível em: [Termo de abertura de projeto](https://github.com/fga-eps-mds/Tema-02/blob/main/docs/TAP.md)
