### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by eng-Bruno** [fga-eps-mds/Tema-02#11]
# Descrição
Elaborar documento de visão.

# Tarefas
- [x] Definir modelo a ser seguido
- [x] Iniciar elaboração do documento
- [x] Definir  o escopo do projeto baseado nas funcionalidades definidas no jamboard

# Critérios de aceitação
- [x] Revisão do documento
- [x] Subir documento no git

**Comment by GabriellyAssuncao** [comment]
https://jamboard.google.com/d/19E6pWMAq4OtFcOsfH4DOHFpENRbrybQEOP6AZ6QSpbg/viewer?f=0
