### ISSUE TITLE
Documento de Arquitetura 

### ISSUE THREAD

**Issue by eng-Bruno** [fga-eps-mds/Tema-02#12]
# Descrição
Elaborar documento de arquitetura.

# Tarefas
- [x] Definir modelo a ser seguido
- [x] Implementar o diagrama UML.
- [x] Determinar tecnologias a serem utilizadas.
- [x] Descrever detalhadamente o escopo do projeto incluindo possíveis restrições.

# Critérios de aceitação
- [x] Revisão do documento
- [x] Subir documento no git

**Comment by Madu01** [comment]
Disponível em [Documento de Arquitetura](https://github.com/fga-eps-mds/Tema-02/blob/main/docs/DocumentoDeArquitetura.md)

**Comment by Madu01** [comment]
Exemplos de documentos de arquitetura (para ajudar no desenvolvimento do nosso): 
[Exemplo 1](https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document?id=_1-introdu%c3%a7%c3%a3o) 
[Exemplo 2 (baixar o arquivo CadernoArquiteturaExemplo.docx)](https://www.trt9.jus.br/pds/pdstrt9/guidances/examples/caderno_arquitetura_CB56CF3C.html)
[Exemplo 3](http://www.linhadecodigo.com.br/artigo/3343/como-documentar-a-arquitetura-de-software.aspx)

**Comment by vitormanoel17** [comment]
Decidimos tomar como referência a documentação de arquitetura do projeto [Acacia](https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document)

**Comment by Madu01** [comment]
As tecnologias base decididas são: 

- HTML
-  CSS
- JavaScript 
- Web Scraper

(Obs.: Pode ocorrer a acrescentação de mais uma tecnologia)

**Comment by Elios630** [comment]
Foi revisado os subtópicos 2.1 e 2.2 do documento de Arquitetura.
