### ISSUE TITLE
Dojo de github

### ISSUE THREAD

**Issue by eng-Bruno** [fga-eps-mds/Tema-02#13]
# Descrição
Realizar dojo de treinamento de github.
* Dojo será realizado pelos scrum master
* Dojo será realizada por meio de reuniões previamente marcadas

# Tarefas
- [x] Marcar um horário pra realizar o dojo
- [x] Dojo através de reunião

# Critérios de aceitação
- [x] Realizações do dojo sobre o tema

**Comment by laisramos123** [comment]
### Segue documento de apresentação do Dojo realizado:
[Git e Github (2).pptx](https://github.com/fga-eps-mds/Tema-02/files/8075543/Git.e.Github.2.pptx)
