### ISSUE TITLE
Pesquisa sobre as tecnologias

### ISSUE THREAD

**Issue by eng-Bruno** [fga-eps-mds/Tema-02#15]
# Descrição

Após a definição das tecnologias que serão utilizados no projeto, elaborar:

# Tarefas
- [x] Estudar tecnologias

# Critérios de aceitação
- [x] Tutorial de ambientação
- [x] Links, referências bibliográficas

**Comment by GabriellyAssuncao** [comment]
Links utilizados para ambientação:
- https://developer.chrome.com/docs/extensions/mv3/architecture-overview/
- https://www.treinaweb.com.br/blog/instalando-e-gerenciando-varias-versoes-do-node-js-com-nvm
- https://pptr.dev/
- https://docs.microsoft.com/pt-br/windows/dev-environment/javascript/vue-on-wsl
