### ISSUE TITLE
Quadro de conhecimentos

### ISSUE THREAD

**Issue by LuizPettengill** [fga-eps-mds/Tema-02#16]
# Descrição

Preencher a cada sprint sua evolução nos conhecimentos trabalhados no projeto.
https://docs.google.com/spreadsheets/d/1Nei27dYchQhfR90xS8_QOrHhE24tfpM9wQXdR4A_QXg/edit?usp=sharing

# Tarefas
- [x] Preencher quadro de conhecimento

# Critérios de aceitação
- [x] Seguir padrão de cores

**Comment by beatrizSO** [comment]
Preenchimento do quadro de conhecimentos seguindo padrão de cores concluído.

**Comment by ahbreu** [comment]
Preenchimento concluído!
