### ISSUE TITLE
Documentação sprint 3

### ISSUE THREAD

**Issue by LuizPettengill** [fga-eps-mds/Tema-02#33]
# Descrição
Elaborar a documentação da sprint 3, mostrando o que foi apresentado durante a semana de forma breve.

# Tarefas
- [x] Documentar sprint 3

# Critérios de Aceitação
- [x] Documento do planejamento da sprint 3
- [x] Documento do resultado da sprint 3

**Comment by GabriellyAssuncao** [comment]
O documento de planejamento da sprint 3 foi enviado ao reposítorio e revisado.

**Comment by GabriellyAssuncao** [comment]
O documento referente ao resultado da sprint 3 foi enviado para a revisão.
