### ISSUE TITLE
Compreensão a respeito de Metodologias Ágeis

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/Tema-02#4]
# Descrição
Estudo dos principais tipos de metodologias ágeis e suas formas de aplicação.
# Tarefas
### 1. Metodologias a serem estudadas:
- [x] Kanban
- [x] Scrum
- [x] XP
- [x] Lean

#### Grupo A
- [x] Tarefa Concluída
#### Grupo B
- [x] Tarefa Concluída

**Comment by RochaCarla** [comment]
Cadê a evidencia que essa tarefa foi finalizada? qual o entregáveis da tarefa?
ex: links uteis, link para o treinamento, slides etc

**Comment by laisramos123** [comment]
## Documentos do treinamento sobre metodologias ágeis  feito junto à equipe

- [Metodologias Ágeis.pdf](https://github.com/fga-eps-mds/Tema-02/files/7978772/Metodologias.Ageis.pdf)

- [Métodologias ágeis.pdf](https://github.com/fga-eps-mds/Tema-02/files/7978774/Metodologias.ageis.pdf)
