### ISSUE TITLE
Guia de contribuição

### ISSUE THREAD

**Issue by vitormanoel17** [fga-eps-mds/Tema-02#42]
## Descrição
Desenvolver o documento do guia de contribuição

## Tarefas

- [x]  Definir o modelo a ser seguido
- [x]  Dividir entre os membros as tarefas individuais a serem feitas

## Critérios de aceitação

- [ ]  Revisão do documento
- [x]  Documento deve estar no repositório do git

**Comment by vitormanoel17** [comment]
Foram adicionados os tópicos: Politicas de commit e Politicas de Pull Request

**Comment by Madu01** [comment]
já foram adicionados os tópicos: "Política de branches" e "Política de desenvolvimento"

**Comment by Madu01** [comment]
Disponível em: [Guia de Contribuição](https://github.com/fga-eps-mds/Tema-02/blob/main/docs/DocumentoDeContribuicao.md)

**Comment by GabriellyAssuncao** [comment]
Documento revisado
