### ISSUE TITLE
Template Pull Requests

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/Tema-02#44]
### Descrição:
Definir um template para a criação de pull requests

### Tarefas:

- [x]  Criar template
- [x]  Padronizar os próximos pull requests

### Critérios de aceitação:

- [x]  Revisão do documento
- [x]  Subir o documento no git

**Comment by GabriellyAssuncao** [comment]
O template para os pull requests foi criado, enviado ao repositório e submetido a revisão.

**Comment by laisramos123** [comment]
Template foi revisado e aprovado!
