### ISSUE TITLE
Template para Issues "bug report"

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/Tema-02#49]
### Descrição:

Definir um template para a criação de issues "bug report"

### Tarefas:

- [x]  Criar modelo a ser seguido
- [x]  Padrozinar as próximas issues

### Critérios de aceitação:

- [x]  Revisão do documento
- [x]  Subir o documento no git

**Comment by GabriellyAssuncao** [comment]
O template das issues de bug report foi criado, enviado ao repositório e submetido a revisão.

**Comment by laisramos123** [comment]
O template foi revisada e aprovada!
