### ISSUE TITLE
Definição das funções dentro dos times

### ISSUE THREAD

**Issue by laisramos123** [fga-eps-mds/Tema-02#5]
# Descrição
Estudo e aplicação das funções presentes nas metodologias ágeis.

# Tarefas

#### Grupo A
- [x] Tarefa concluída
#### Grupo B
- [x] Tarefa concluída

#### Grupo A
- [x] Tarefa concluída
### Grupo B
- [x] Tarefa concluída

**Comment by 16bits** [comment]
#### Grupo A
- Scrum masters: @LuizPettengill, @eng-Bruno
- Product Owners: @beatrizSO, @EduardaSMarques
- Arquitetos: @Madu01, @16bits

**Comment by GabriellyAssuncao** [comment]
### Grupo A 
- Scrum Master: @laisramos123 @GabriellyAssuncao 
- Product Owner: @HianPraxedes @Elios630 
- Arquitetos: @vitormanoel17 @ahbreu

**Comment by GabriellyAssuncao** [comment]
### Definição - Scrum Master
- O Scrum Master é o responsável por garantir que o time se oriente pelos valores e práticas do Scrum. O Scrum Master protege o time, certificando-se de que os membros não se comprometam com demandas além dos que eles conseguem cumprir dentro de uma Sprint. O Scrum Master facilita a Reunião Diária (Daily Scrum) e se torna o responsável pela remoção de quaisquer obstáculos observados pelo time durante estas reuniões.

https://www.trt9.jus.br/pds/Scrum/roles/scrummaster_357FCB70.html

**Comment by Madu01** [comment]
### Definição - Arquiteto de software

- O arquiteto lidera e coordena as tarefas e os artefatos técnicos no desenvolvimento do projeto (como o design, os padrões de codificação de software, as ferramentas, e as plataformas a serem utilizadas). De forma mais técnica o arquiteto desempenha e estabelece a base e a estrutura geral de cada panorama da arquitetura de um software:  a decomposição da visão, o agrupamento dos elementos e as interfaces entre esses principais agrupamentos.
#### Fontes:
https://www.trt9.jus.br/pds/pdstrt9/roles/architect_E7A12309.html
https://www.freelancermap.com/blog/pt/o-que-faz-arquiteto-de-software/#Fun%C3%A7%C3%B5es

**Comment by EduardaSMarques** [comment]
# Definição - Product Owner
* O Product Owner representa os interesses de todos os envolvidos, define as funcionalidades do produto e prioriza os itens de Product Backlog. Ou seja, o Product Owner é responsável por maximizar o valor do produto resultante do trabalho da Scrum
Team

#### Fontes:

https://www.trt9.jus.br/pds/Scrum/roles/product_owner_10E7BD3.html
https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-Portuguese-European.pdf
