### ISSUE TITLE
Definição da dinâmica dos grupos - Horários

### ISSUE THREAD

**Issue by 16bits** [fga-eps-mds/Tema-02#6]
# Descrição
Conhecer os horários disponíveis de cada membro dos dois grupos e definir os melhores horários para as reuniões.

# Tarefas

#### Grupo A
- [X] Tarefa concluída
#### Grupo B
- [X] Tarefa concluída

#### Grupo A
- [X] Tarefa concluída
### Grupo B
- [X] Tarefa concluída

## 3. Reunião inicial com os dois grupos juntos para definir os melhores horários para o todo o time do Tema 2
- [x] Tarefa concluída

**Comment by 16bits** [comment]
Tabela de horários do Grupo B:
[Horários do Grupo B](https://docs.google.com/spreadsheets/d/1QeUC2tIB6eVCd6rUt98XX8EROFr8DddoaTS0BnVCwmA/edit?usp=sharing)

**Comment by 16bits** [comment]
Tabela de horários do Grupo A:
[Horários do Grupo A](https://docs.google.com/spreadsheets/d/176W2iaYAIZKE01Pt3BL85hMgYckSddU5jqIW_6l427w/edit?usp=sharing)

**Comment by laisramos123** [comment]
### Foi decidido que as reuniões fixas  dos dois grupos seriam divididos  de duas formas: 

- De acordo com os  papéis e times (Terça-Feira 19h)
- Com o grupo todo (Quinta-feira 19h)

#### Caso necessite de mais alguma reunião, os times ficam livres para decidir dia e horário
