### ISSUE TITLE
Adicionar GitHub Page ao Repositório

### ISSUE THREAD

**Issue by GabriellyAssuncao** [fga-eps-mds/Tema-02#61]
### Descrição:
Desenvolver Github Page

### Tarefas:

- [x]  Iniciar o desenvolvimento
- [x]  Realizar teste
- [x]  Adicionar no git

### Critérios de aceitação:

- [x]  Página funcionando
- [x]  Revisão

**Comment by laisramos123** [comment]
Página testada e revisada! A mesma será aprimorada ao longo do tempo!
