### ISSUE TITLE
Correção da política de branches

### ISSUE THREAD

**Issue by Madu01** [fga-eps-mds/Tema-02#62]
### Descrição:
Atualizar a política de branches do guia de contribuição para um modelo mais simples.

### Tarefas:
Checklist de ações que devem ser realizadas.

- [x]  Atualização da  política de branches

### Critérios de aceitação:
Definir os critérios para a issue ser considerada concluída.

- [x] Revisar documento

**Comment by GabriellyAssuncao** [comment]
Documento revisado
