### ISSUE TITLE
Pesquisa sobre soluções alternativas web scraping

### ISSUE THREAD

**Issue by vitormanoel17** [fga-eps-mds/Tema-02#69]
### Descrição:
Realizar pesquisa relacionada a soluções alternativas, para desenvolver um meio de fazer web scraping em área logada com puppeteer (preferencialmente) ou outras bibliotecas, sem utilizar senhas do usuário.
### Tarefas:

- [x] levantar dados relevantes em busca de uma solução
- [x] buscar ajuda em fóruns  

### Critérios de aceitação:

- [x]  encontrar solução

**Comment by GabriellyAssuncao** [comment]
https://adrianosantospb.medium.com/realizando-web-scraping-em-ambientes-que-necessitam-de-autentica%C3%A7%C3%A3o-15d3e5cbacf1

**Comment by GabriellyAssuncao** [comment]
http://kazuar.github.io/scraping-tutorial/

**Comment by GabriellyAssuncao** [comment]
https://github.com/adrianosantospb/webscrapingnotwiki

**Comment by GabriellyAssuncao** [comment]
https://github.com/pablomuro/puppeteer-cluster#examples

**Comment by GabriellyAssuncao** [comment]
https://github.com/pablomuro/sigaa-unb-volta-horario

**Comment by vitormanoel17** [comment]
Foi decidido realizar a mineração dos dados na página do SIGAA (Área logada) por meio da manipulação do DOM utilizando JavaScript, evitando a utilização de bibliotecas de web Scraping, e assim sendo uma opção mais segura e sem necessidade de dados sensíveis pertencentes ao usuário.
